name: Deploy no AWS Elastic Beanstalk

on:
  push:
    branches:
      - master      
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BASE_AWS_URL: ${{ secrets.BASE_AWS_URL }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Gerar arquivo .env
        run: |
          echo "BASE_AWS_URL=${BASE_AWS_URL}" > .env    

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Empacotar código
        run: zip -r deploy.zip .

      - name: Enviar bundle para S3
        run: |
          aws s3 cp deploy.zip \
            s3://elasticbeanstalk-us-east-1-107193530096/deploy-${{ github.sha }}.zip

      - name: Criar nova versão do Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name front-end-deploy \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-107193530096",S3Key="deploy-${{ github.sha }}.zip"

      - name: Atualizar ambiente no Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name front-end-deploy-env \
            --version-label ${{ github.sha }}